
INSERT INTO materia (nome, descricao, creditos) VALUES
('Português Instrumental', 'Desenvolvimento da comunicação escrita e falada.', 4),
('Fundamentos da Contabilidade', 'Conceitos básicos de contabilidade.', 4),
('Metodologia da Pesquisa', 'Técnicas de pesquisa acadêmica e científica.', 4),
('Álgebra Linear', 'Sistemas lineares, vetores e matrizes.', 4),
('Pesquisa Operacional I', 'Modelagem e otimização de processos.', 4),
('Noções Básicas de Programação', 'Fundamentos da lógica de programação.', 4),
('Programação de Computadores I', 'Programação estruturada com linguagem de alto nível.', 4),
('Programação de Computadores II', 'Conceitos avançados e introdução à orientação a objetos.', 4),
('Estrutura de Dados I', 'Listas, pilhas, filas.', 4),
('Estrutura de Dados II', 'Árvores, grafos e algoritmos.', 4),
('Sistemas Operacionais I', 'Conceitos básicos de sistemas operacionais.', 4),
('Sistemas Operacionais II', 'Gerência de processos, memória e arquivos.', 4),
('Empreendedorismo e Gestão Estratégica', 'Conceitos de negócios e planejamento.', 4),
('Gerência de Sistemas e Projetos', 'Gestão de projetos de sistemas.', 4),
('Trabalho de Conclusão de Curso I', 'Planejamento do projeto final.', 4),
('Trabalho de Conclusão de Curso II', 'Execução e entrega do projeto final.', 4),
('Estágio Supervisionado I', 'Experiência prática supervisionada.', 4),
('Estágio Supervisionado II', 'Continuação do estágio supervisionado.', 4),
('Introdução à Lógica', 'Lógica formal e proposicional.', 4),
('Organização de Computadores I', 'Arquitetura básica.', 4),
('Organização de Computadores II', 'Arquitetura avançada.', 4),
('Gerência de Projetos', 'Gestão de escopo, tempo, qualidade e risco.', 4),
('Análise de Sistemas I', 'Modelagem e levantamento de requisitos.', 4),
('Análise de Sistemas II', 'Modelagem avançada e estudos de caso.', 4),
('Projeto de Sistemas I', 'Desenvolvimento de projetos básicos.', 4),
('Projeto de Sistemas II', 'Continuação e implementação de projetos.', 4),
('Banco de Dados I', 'Modelagem relacional.', 4),
('Banco de Dados II', 'SQL avançado e procedimentos.', 4),
('Banco de Dados III', 'Desempenho e administração.', 4),
('Desenvolvimento de Sistemas I', 'Desenvolvimento em ambiente desktop.', 4),
('Desenvolvimento de Sistemas II', 'Aplicações distribuídas.', 4),
('Desenvolvimento para Dispositivos Móveis', 'Aplicações Android/iOS.', 4),
('UX e Desenvolvimento Web', 'Experiência do usuário e front-end.', 4),
('Qualidade de Software', 'Testes, métricas e melhoria contínua.', 4),
('Sistemas de Informação Gerenciais', 'Gestão da informação e sistemas empresariais.', 4),
('Optativa I', 'Disciplina eletiva.', 4),
('Optativa II', 'Disciplina eletiva.', 4),
('Optativa III', 'Disciplina eletiva.', 4),
('Introdução à Redes de Computadores', 'Topologias e protocolos.', 4),
('Gestão de Redes', 'Administração e segurança.', 4),
('Filosofia e Ética', 'Reflexão crítica e ética profissional.', 4),
('Cálculo Diferencial e Integral A', 'Limites, derivadas e integrais.', 4),
('Cálculo Diferencial e Integral B', 'Integrais múltiplas e séries.', 4),
('Matemática Discreta', 'Conjuntos, lógica e grafos.', 4),
('Cálculo Numérico (S.I.)', 'Métodos numéricos aplicados à computação.', 4),
('Estatística e Probabilidade', 'Distribuições e testes.', 4),
('Inferência Estatística', 'Estimativas, testes de hipóteses.', 4),
('Estruturas Organizacionais', 'Modelos de organização empresarial.', 4);
